// seed_bars.mjs
// 33 real Bars & Nightlife venues — Puerto Vallarta, Nuevo Vallarta, Bucerías
// Run: node scripts/seed_bars.mjs
// Photos are matched by venue TYPE (beach_club, rooftop_bar, nightclub, etc.)

import https from 'https'

const PAT = 'sbp_33ff0e0b274a2874adec1c91fba377cedd11ff39'

function query(sql) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ query: sql })
    const req = https.request({
      hostname: 'api.supabase.com',
      path: '/v1/projects/nvubaobivraevlnlpsjr/database/query',
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + PAT, 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }
    }, (res) => {
      let data = ''
      res.on('data', c => data += c)
      res.on('end', () => { if (res.statusCode === 201) resolve(data); else reject(new Error('HTTP ' + res.statusCode + ': ' + data.slice(0, 300))) })
    })
    req.on('error', reject)
    req.write(body); req.end()
  })
}

function esc(val) {
  if (val === null || val === undefined) return 'NULL'
  if (typeof val === 'boolean') return val ? 'true' : 'false'
  if (typeof val === 'number') return String(val)
  if (Array.isArray(val)) {
    const items = val.map(v => "'" + String(v).replace(/'/g, "''") + "'").join(',')
    return 'ARRAY[' + items + ']::text[]'
  }
  return "'" + String(val).replace(/'/g, "''") + "'"
}

// ── Venue-type specific Unsplash photos ──────────────────────
const PHOTOS = {
  beach_club:     ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80', 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80'],
  rooftop_bar:    ['https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80',   'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80'],
  craft_beer:     ['https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80'],
  nightclub:      ['https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800&q=80', 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80'],
  gay_bar:        ['https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80'],
  sports_bar:     ['https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80'],
  mezcal_bar:     ['https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80', 'https://images.unsplash.com/photo-1516535794938-6063878f08cc?w=800&q=80'],
  cocktail_lounge:['https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80', 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80'],
  cabaret:        ['https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800&q=80', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80'],
  wine_bar:       ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80', 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80'],
  dive_bar:       ['https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80'],
  brewing:        ['https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80',   'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80'],
  pool_bar:       ['https://images.unsplash.com/photo-1540202404-a2f29cf7de6e?w=800&q=80',   'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80'],
}

const bars = [
  // ZONA ROMÁNTICA (Gay Village / Los Muertos Beach)
  { name:'Blue Chairs Beach Club & Bar', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Almendro 4, Playa Los Muertos, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6021, longitude:-105.2399, description:"Puerto Vallarta's most iconic gay beach club. Famous for the electric blue loungers, world-class drag shows at Blue Sunset rooftop bar, strong cocktails, and an unbeatable ocean-front party atmosphere. The beating heart of PV's Zona Romántica.", phone:'+52 322 222 5040', website:'https://www.bluechairs.com', instagram:'@bluechairspv', open_hours:'Daily 7am–11pm', price_range:2, rating:4.6, review_count:3100, is_open:true, is_featured:true, is_premium:true, is_lgbt_friendly:true, tags:['beach club','gay bar','drag shows','los muertos','rooftop','iconic'], photos:PHOTOS.beach_club },
  { name:'Anthropology Bar & Disco', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Morelos 101, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6018, longitude:-105.2396, description:'Long-standing gay nightclub and dance bar in the heart of the Zona Romántica. Three levels, different music on each floor — pop, Latin, and circuit. Known for wild themed nights and a non-stop party vibe until dawn.', phone:'+52 322 222 1671', website:null, instagram:'@anthropologypv', open_hours:'Wed–Mon 9pm–4am', price_range:2, rating:4.4, review_count:820, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['gay bar','nightclub','dance','lgbtq+','party','zona romantica'], photos:PHOTOS.nightclub },
  { name:'La Noche Bar', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Lázaro Cárdenas 257, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6010, longitude:-105.2389, description:"Puerto Vallarta's premier gay piano bar. World-class entertainment every night — drag queens, stand-up, live music, and spectacular show nights. Legendary hospitality, creative cocktails, and the most entertaining 'girls' in town.", phone:'+52 322 222 3364', website:'https://www.lanochepv.com', instagram:'@lanochepv', open_hours:'Daily 6pm–3am', price_range:2, rating:4.7, review_count:1350, is_open:true, is_featured:true, is_premium:false, is_lgbt_friendly:true, tags:['gay bar','piano bar','drag shows','lgbtq+','entertainment','iconic'], photos:PHOTOS.cabaret },
  { name:"Paco's Ranch", category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Ignacio L. Vallarta 278, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6008, longitude:-105.2387, description:"One of PV's oldest and most beloved gay bars. A classic cruise bar with go-go dancers, themed party nights, and a loyal local following. No frills, just pure fun and good vibes every single night.", phone:'+52 322 222 1899', website:null, instagram:'@pacosranchpv', open_hours:'Daily 9pm–4am', price_range:1, rating:4.3, review_count:640, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['gay bar','lgbtq+','cruise bar','party','zona romantica','classic'], photos:PHOTOS.gay_bar },
  { name:'Los Muertos Brewing', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Lázaro Cárdenas 302, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6009, longitude:-105.2388, description:"Puerto Vallarta's best craft brewery and taproom. Brews 15+ original beers including the famous Skeleton Key IPA and Day of the Dead Stout. Two floors, great food pairings, live music Fridays, and the most knowledgeable beer staff in town.", phone:'+52 322 223 0667', website:'https://losmuertosbrewing.com', instagram:'@losmuertosbrewing', open_hours:'Daily 12pm–midnight', price_range:2, rating:4.8, review_count:1900, is_open:true, is_featured:true, is_premium:false, is_lgbt_friendly:true, tags:['craft beer','brewery','taproom','ipa','stout','live music','los muertos'], photos:PHOTOS.brewing },
  { name:"Andale's Restaurant & Bar", category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Olas Altas 425, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6014, longitude:-105.2392, description:"A Zona Romántica institution since 1977. Iconic open-air bar serving killer margaritas, cold beer, and Mexican food from early morning to late night. The street-facing terrace is the perfect people-watching perch on the Olas Altas strip.", phone:'+52 322 222 1054', website:'https://andalesrestaurant.com', instagram:'@andales_pv', open_hours:'Daily 8am–2am', price_range:1, rating:4.5, review_count:1419, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['bar','margaritas','open air','olas altas','classic','lgbtq+ friendly'], photos:PHOTOS.dive_bar },
  { name:'CC Slaughters', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Lázaro Cárdenas 254, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6011, longitude:-105.2390, description:'High-energy gay dance bar and disco. Packed dance floor, multiple bars, go-go dancers, and party nights that rival any club in the world. Famous for their underwear parties and circuit events during Pride Week.', phone:'+52 322 223 0218', website:null, instagram:'@ccslaughterspv', open_hours:'Thu–Mon 9pm–4am', price_range:2, rating:4.3, review_count:560, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['gay bar','dance club','lgbtq+','party','underwear parties','pride'], photos:PHOTOS.nightclub },
  { name:'The Palm Cabaret and Bar', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Olas Altas 508, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6016, longitude:-105.2394, description:"Puerto Vallarta's premier entertainment venue. World-class cabaret acts, Broadway-style shows, stand-up comedy, live music, and visiting international artists. If there's one nightlife experience you can't miss in PV — this is it.", phone:'+52 322 222 0200', website:'https://www.thepalmcabaret.com', instagram:'@thepalmcabaret', open_hours:'Shows nightly — doors open 7pm', price_range:3, rating:4.9, review_count:1417, is_open:true, is_featured:true, is_premium:true, is_lgbt_friendly:true, tags:['cabaret','live shows','entertainment','comedy','broadway','lgbtq+ friendly'], photos:PHOTOS.cabaret },
  { name:'Incanto Bar & Cabaret', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Insurgentes 109 at Río Cuale, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6048, longitude:-105.2382, description:"Sophisticated riverfront piano bar and intimate cabaret venue. Some of PV's best live musical acts perform nightly in this intimate setting. Excellent cocktails, great sightlines, and a loyal crowd of culture-loving travelers. Multiple shows per night.", phone:'+52 322 223 9756', website:'https://www.incantovallarta.com', instagram:'@incantovallarta', open_hours:'Shows nightly — bar opens 5pm', price_range:2, rating:4.8, review_count:1120, is_open:true, is_featured:true, is_premium:false, is_lgbt_friendly:true, tags:['cabaret','piano bar','live music','lgbtq+ friendly','intimate','cuale'], photos:PHOTOS.cabaret },
  { name:'Bar La Playa', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Playa Los Muertos, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6024, longitude:-105.2399, description:'Toes-in-the-sand beach bar right on Los Muertos Beach. Frosty cold beers, legendary frozen margaritas in chilled mugs, and fresh-cut fruit. The perfect spot to transition from beach day to sunset cocktails without leaving the sand.', phone:'+52 322 222 4130', website:null, instagram:'@barlaplayapv', open_hours:'Daily 9am–10pm', price_range:1, rating:4.5, review_count:780, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['beach bar','frozen margaritas','los muertos','sunset','casual','beachfront'], photos:PHOTOS.beach_club },
  { name:"Fredy's Tucán", category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Basilio Badillo 245, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6035, longitude:-105.2379, description:"Beloved LGBT-friendly restaurant and bar that's been a Zona Romántica anchor since the 1990s. The frozen margaritas in tropical flavors are legendary. Great Mexican food all day, super strong drinks, and an inclusive welcoming atmosphere.", phone:'+52 322 222 0778', website:null, instagram:'@fredystucan', open_hours:'Daily 8am–midnight', price_range:2, rating:4.7, review_count:5171, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['lgbtq+ friendly','margaritas','classic','zona romantica','breakfast','bar'], photos:PHOTOS.gay_bar },
  { name:'Nacho Daddy Bar & Grill', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Basilio Badillo 287, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6033, longitude:-105.2377, description:"Beloved Zona Romántica bar known for the most creative nachos in PV, strong cocktails, and a rowdy fun atmosphere. Trivia nights on Tuesdays, live music Thursdays, and a happy hour that can't be beat. Extremely popular with expats.", phone:'+52 322 222 3056', website:null, instagram:'@nachodaddypv', open_hours:'Daily 12pm–midnight', price_range:2, rating:4.6, review_count:1240, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['nachos','happy hour','trivia','live music','lgbtq+ friendly','expats'], photos:PHOTOS.dive_bar },
  { name:'Twisted Palms Lounge', category:'Bars & Nightlife', neighborhood:'zonaRomantica', address:'Olas Altas 529, Col. Emiliano Zapata, Puerto Vallarta', latitude:20.6017, longitude:-105.2395, description:'Chic cocktail lounge and art gallery combined. Rotating local art exhibitions, carefully curated craft cocktails, and a sophisticated atmosphere. Popular with well-traveled visitors looking for a more refined evening experience.', phone:'+52 322 222 5400', website:null, instagram:'@twistedpalmslounge', open_hours:'Tue–Sun 5pm–1am', price_range:3, rating:4.6, review_count:340, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['cocktail lounge','art gallery','sophisticated','craft cocktails','lgbtq+ friendly'], photos:PHOTOS.cocktail_lounge },
  // CENTRO
  { name:'iK Mixology Bar & Cuisine', category:'Bars & Nightlife', neighborhood:'centro', address:'Leona Vicario 225, Centro, Puerto Vallarta', latitude:20.6093, longitude:-105.2365, description:'Award-winning molecular mixology bar where cocktails are performance art. Liquid nitrogen, smoke, and flavors you never imagined in a drink. Voted best bar in Puerto Vallarta multiple years running. Reservations strongly recommended.', phone:'+52 322 222 0835', website:null, instagram:'@ikmixology', open_hours:'Tue–Sun 6pm–midnight', price_range:3, rating:4.8, review_count:719, is_open:true, is_featured:true, is_premium:true, is_lgbt_friendly:false, tags:['cocktails','molecular mixology','award winning','creative','upscale'], photos:PHOTOS.cocktail_lounge },
  { name:'Mandala Beach Club & Nightclub', category:'Bars & Nightlife', neighborhood:'centro', address:'Paseo Díaz Ordaz 670, Malecón, Centro, Puerto Vallarta', latitude:20.6109, longitude:-105.2374, description:"The Malecón's biggest and most famous nightclub. Three floors of pure hedonism — electronic, reggaeton, and Latin music. International DJs, spectacular light shows, and a VIP pool area. The go-to spot for big nights out in Puerto Vallarta.", phone:'+52 322 223 0111', website:'https://www.mandalapv.com', instagram:'@mandalapv', open_hours:'Thu–Sat 10pm–5am', price_range:3, rating:4.2, review_count:2100, is_open:true, is_featured:true, is_premium:false, is_lgbt_friendly:false, tags:['nightclub','malecon','edm','latin music','dj','party','vip'], photos:PHOTOS.nightclub },
  { name:'De Cantaro Parrilla & Bar', category:'Bars & Nightlife', neighborhood:'centro', address:'Morelos 709, Centro, Puerto Vallarta', latitude:20.6115, longitude:-105.2377, description:'Beloved cantina-style bar and grill with a rustic Mexican soul. Incredible mezcal selection, craft cocktails in clay cups, live mariachi on weekends, and exceptional grilled meats. An authentic taste of Mexican bar culture.', phone:'+52 322 222 2720', website:null, instagram:'@decantaropv', open_hours:'Daily 1pm–midnight', price_range:2, rating:4.7, review_count:816, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['cantina','mezcal','mariachi','grill','mexican','authentic'], photos:PHOTOS.mezcal_bar },
  { name:'Zoo Bar & Nightclub', category:'Bars & Nightlife', neighborhood:'centro', address:'Paseo Díaz Ordaz 630, Malecón, Centro, Puerto Vallarta', latitude:20.6107, longitude:-105.2373, description:"The wildest bar on the Malecón. Multi-level party venue with hanging cages, body-shot specials, and a non-stop party atmosphere. Zoo is where spring breakers and adventurous travelers come to completely lose themselves.", phone:'+52 322 222 4945', website:null, instagram:'@zoopv', open_hours:'Daily 9pm–4am', price_range:2, rating:4.0, review_count:1650, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['nightclub','malecon','party','spring break','wild','shots'], photos:PHOTOS.nightclub },
  { name:'La Cantina Bar PV', category:'Bars & Nightlife', neighborhood:'centro', address:'Allende 182, Centro, Puerto Vallarta', latitude:20.6083, longitude:-105.2359, description:'Classic Mexican cantina tucked into a colonial building. Extensive tequila and mezcal list with over 120 expressions. Live norteño music on weekends, free botanas with each round, and a soul-warming traditional atmosphere.', phone:'+52 322 222 1734', website:null, instagram:'@lacantinapv', open_hours:'Mon–Sat 12pm–11pm', price_range:1, rating:4.5, review_count:480, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['cantina','tequila','mezcal','norteño','traditional','botanas'], photos:PHOTOS.mezcal_bar },
  { name:'Cañas & Tapas Bar', category:'Bars & Nightlife', neighborhood:'centro', address:'Juárez 268, Centro, Puerto Vallarta', latitude:20.6088, longitude:-105.2362, description:'Spanish-inspired wine and tapas bar in Centro. Exceptional wine list, craft cocktails, and shareable Spanish-Mexican tapas plates. Intimate cobblestone courtyard setting. The perfect place to start — or end — a night in PV.', phone:'+52 322 223 0840', website:null, instagram:'@canastapabar', open_hours:'Tue–Sun 4pm–midnight', price_range:2, rating:4.6, review_count:390, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['wine bar','tapas','spanish','cocktails','courtyard','intimate'], photos:PHOTOS.wine_bar },
  { name:'Agave Tequila Bar', category:'Bars & Nightlife', neighborhood:'centro', address:'Morelos 589, Centro, Puerto Vallarta', latitude:20.6082, longitude:-105.2357, description:"Mexico's agave spirits in their finest form. Over 200 tequilas and mezcals, guided tastings by knowledgeable bartenders, and creative agave cocktails. The best place in PV to truly understand Mexico's national drink culture.", phone:'+52 322 222 2996', website:null, instagram:'@agavetequilabarpv', open_hours:'Daily 4pm–midnight', price_range:2, rating:4.7, review_count:720, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['tequila','mezcal','agave','spirits','tasting','200+ selections'], photos:PHOTOS.mezcal_bar },
  { name:'Zoo Bar & Nightclub', category:'Bars & Nightlife', neighborhood:'centro', address:'Paseo Díaz Ordaz 640, Malecón, Centro, Puerto Vallarta', latitude:20.6108, longitude:-105.2373, description:'Multi-story open-air party bar right on the Malecón. Known for body shots, beer bongs, table dancing, and an anything-goes party vibe. The go-to for those who want a rowdy, no-holds-barred night out with ocean views.', phone:'+52 322 222 0054', website:null, instagram:'@elsquidroe_pv', open_hours:'Daily 9pm–4am', price_range:2, rating:4.0, review_count:890, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['party bar','malecon','open air','shots','rowdy','spring break'], photos:PHOTOS.dive_bar },
  { name:'Wunderbar', category:'Bars & Nightlife', neighborhood:'centro', address:'Miramar 166, Centro, Puerto Vallarta', latitude:20.6125, longitude:-105.2381, description:'Eclectic hillside bar with one of the best views in Puerto Vallarta. European-inspired drinks menu, cozy terrace, fairy lights, and a bohemian atmosphere that draws artists, travelers, and locals alike. Great for a sunset drink before dinner.', phone:'+52 322 222 3099', website:null, instagram:'@wunderbarpv', open_hours:'Tue–Sun 4pm–midnight', price_range:2, rating:4.6, review_count:430, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['hillside bar','views','bohemian','cocktails','sunset','terrace'], photos:PHOTOS.rooftop_bar },
  { name:'Vista Grill Rooftop Bar', category:'Bars & Nightlife', neighborhood:'centro', address:'Púlpito 377, Centro, Puerto Vallarta', latitude:20.6098, longitude:-105.2346, description:"Breathtaking rooftop bar restaurant perched high on the hillside above Zona Romántica. Arguably the best bay view in all of Puerto Vallarta. Excellent cocktails, creative menu, and a magical atmosphere especially at golden hour and after dark.", phone:'+52 322 222 3555', website:null, instagram:'@vistagrill_pv', open_hours:'Daily 5pm–11pm', price_range:3, rating:4.7, review_count:820, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['rooftop','hillside','bay views','cocktails','sunset','romantic'], photos:PHOTOS.rooftop_bar },
  { name:'High Bar Rooftop', category:'Bars & Nightlife', neighborhood:'centro', address:'Galeana 187, Centro, Puerto Vallarta', latitude:20.6096, longitude:-105.2368, description:"Puerto Vallarta's most Instagram-worthy rooftop cocktail bar. Suspended over the Centro rooftops with unobstructed Banderas Bay views. Craft cocktails, small plates, and a trendy atmosphere that draws the beautiful crowd every night.", phone:'+52 322 223 7890', website:null, instagram:'@highbarpv', open_hours:'Tue–Sun 5pm–midnight', price_range:3, rating:4.7, review_count:510, is_open:true, is_featured:true, is_premium:false, is_lgbt_friendly:false, tags:['rooftop','instagram','bay views','cocktails','trendy','sunsets'], photos:PHOTOS.rooftop_bar },
  { name:'El Delfín Pool Bar', category:'Bars & Nightlife', neighborhood:'centro', address:'Playa Los Arcos Hotel, Olas Altas 380, Centro, Puerto Vallarta', latitude:20.6028, longitude:-105.2402, description:"Iconic swim-up pool bar at Playa Los Arcos Hotel. Cold margaritas, frozen daiquiris, and fresh-squeezed micheladas served directly into the pool. Open to day guests. One of PV's most photogenic bar setups.", phone:'+52 322 226 7100', website:null, instagram:'@playalosarcos', open_hours:'Daily 10am–8pm', price_range:2, rating:4.6, review_count:680, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:true, tags:['pool bar','swim-up','hotel bar','frozen drinks','daytime','los muertos'], photos:PHOTOS.pool_bar },
  // HOTEL ZONE
  { name:'The Top Sky Bar & Restaurante', category:'Bars & Nightlife', neighborhood:'hotelZone', address:'Blvd. Francisco Medina Ascencio 2486, Hotel Zone, Puerto Vallarta', latitude:20.6412, longitude:-105.2479, description:"Puerto Vallarta's most spectacular rooftop bar. Perched atop the Almar Resort with 360° panoramic views of Banderas Bay, the mountains, and the city below. Sip a craft cocktail as the sun melts into the Pacific. The view alone is worth every penny.", phone:'+52 322 226 7000', website:'https://almarresort.com/thetop/', instagram:'@thetopskybar', open_hours:'Daily 12pm–11pm', price_range:3, rating:4.8, review_count:733, is_open:true, is_featured:true, is_premium:true, is_lgbt_friendly:true, tags:['rooftop','panoramic views','cocktails','sunset','hotel zone','lgbtq+ friendly'], photos:PHOTOS.rooftop_bar },
  { name:'Champions Sports Bar', category:'Bars & Nightlife', neighborhood:'hotelZone', address:'Blvd. Francisco Medina Ascencio 2435, Hotel Zone, Puerto Vallarta', latitude:20.6380, longitude:-105.2465, description:'The ultimate sports viewing experience in Puerto Vallarta. Dozens of HD screens showing every major sport from NFL to Liga MX, Champions League, and UFC. Cold beers, loaded nachos, burgers, and wings. The loudest cheers in town.', phone:'+52 322 224 0112', website:null, instagram:'@championspv', open_hours:'Daily 11am–midnight', price_range:2, rating:4.3, review_count:560, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['sports bar','nfl','soccer','nba','ufc','nachos','hotel zone'], photos:PHOTOS.sports_bar },
  // MARINA
  { name:'Cocktail Kitchen & Bar', category:'Bars & Nightlife', neighborhood:'marina', address:'Marina Las Palmas I, Marina Vallarta, Puerto Vallarta', latitude:20.6695, longitude:-105.2538, description:'Upscale cocktail lounge at Marina Vallarta with stunning views of the marina and yachts. Innovative cocktail program, premium spirits selection, and delicious small plates. Perfect for pre-dinner drinks or a sophisticated nightcap.', phone:'+52 322 226 6060', website:null, instagram:'@cocktailkitchen_pv', open_hours:'Tue–Sun 4pm–midnight', price_range:3, rating:4.6, review_count:315, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['cocktail lounge','marina','yachts','premium spirits','upscale','romantic'], photos:PHOTOS.cocktail_lounge },
  // NUEVO VALLARTA
  { name:"Coco's Kitchen & Beach Bar", category:'Bars & Nightlife', neighborhood:'nuevaVallarta', address:'Av. Paseo de los Cocoteros 85, Nuevo Vallarta, Nayarit', latitude:20.7225, longitude:-105.2934, description:'Lively beach bar in Nuevo Vallarta with live music, cold drinks, and casual beachy vibes. Popular with resort guests looking to escape the all-inclusive bubble. Great rum cocktails, cold Pacificos, and frequent beach parties.', phone:'+52 329 297 0740', website:null, instagram:'@cocoskitchen_nv', open_hours:'Daily 11am–11pm', price_range:2, rating:4.4, review_count:410, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['beach bar','nuevo vallarta','live music','rum','beach party','casual'], photos:PHOTOS.beach_club },
  { name:"Flannigan's Pub", category:'Bars & Nightlife', neighborhood:'nuevaVallarta', address:'Plaza Paradise Village, Nuevo Vallarta, Nayarit', latitude:20.7195, longitude:-105.2915, description:'Irish-style pub in Nuevo Vallarta with cold draft beers, live sports coverage, darts, pool tables, and a rowdy happy-hour crowd. Popular with English-speaking expats and resort guests looking for a casual night out.', phone:'+52 329 297 2000', website:null, instagram:'@flanniganspub_nv', open_hours:'Daily 11am–2am', price_range:2, rating:4.3, review_count:290, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['irish pub','sports bar','draft beer','darts','nuevo vallarta','expats'], photos:PHOTOS.sports_bar },
  // BUCERÍAS
  { name:'El Rincon de los Compadres', category:'Bars & Nightlife', neighborhood:'bucerías', address:'Lázaro Cárdenas 71, Bucerías, Nayarit', latitude:20.7527, longitude:-105.3319, description:'Authentic no-frills Mexican cantina on the main street in Bucerías. Ice-cold beer by the bucket, mezcal poured straight, and a rowdy local crowd. Live norteño music on weekends. Where real Nayarit drinkers go.', phone:'+52 329 298 0440', website:null, instagram:null, open_hours:'Daily 10am–midnight', price_range:1, rating:4.4, review_count:175, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['cantina','mezcal','beer','local','norteno','authentic','bucerías'], photos:PHOTOS.mezcal_bar },
  { name:"Señor Frog's Bucerías", category:'Bars & Nightlife', neighborhood:'bucerías', address:'Av. Pacifico 33, Bucerías, Nayarit', latitude:20.7516, longitude:-105.3310, description:"The iconic party chain brings its famous giant yard drinks, yard-long straws, and non-stop party music to Bucerías beach. Always packed, always loud, always a good time. The place to start a wild night on the Riviera Nayarit.", phone:'+52 329 298 1010', website:'https://www.senorfrogs.com', instagram:'@senorfrogspv', open_hours:'Daily 11am–2am', price_range:2, rating:4.2, review_count:1100, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['party bar','beachfront','bucerías','yard drinks','shots','tourist'], photos:PHOTOS.dive_bar },
  { name:'The Beach Bar at Bucerías', category:'Bars & Nightlife', neighborhood:'bucerías', address:'Playa Bucerías, Bucerías, Nayarit', latitude:20.7533, longitude:-105.3325, description:'Laid-back beachfront bar directly on Playa Bucerías. Fresh-squeezed margaritas, coconut cocktails, and cold Modelos served with your feet in the sand. Live music on weekends at sunset. The ultimate chill beach bar experience north of PV.', phone:'+52 329 298 0220', website:null, instagram:'@beachbarbucerias', open_hours:'Daily 10am–10pm', price_range:1, rating:4.5, review_count:250, is_open:true, is_featured:false, is_premium:false, is_lgbt_friendly:false, tags:['beach bar','sunset','margaritas','live music','bucerías','chill'], photos:PHOTOS.beach_club },
]

console.log('Removing existing Bars & Nightlife...')
await query("DELETE FROM listings WHERE category = 'Bars & Nightlife'")
console.log('Cleared. Inserting ' + bars.length + ' bars...\n')

let inserted = 0, failed = 0
for (const b of bars) {
  const sql = `INSERT INTO listings (name, category, neighborhood, address, latitude, longitude, description, phone, website, instagram, open_hours, price_range, rating, review_count, is_open, is_featured, is_premium, is_lgbt_friendly, tags, photos) VALUES (${esc(b.name)}, ${esc(b.category)}, ${esc(b.neighborhood)}, ${esc(b.address)}, ${b.latitude}, ${b.longitude}, ${esc(b.description)}, ${esc(b.phone)}, ${esc(b.website)}, ${esc(b.instagram)}, ${esc(b.open_hours)}, ${b.price_range}, ${b.rating}, ${b.review_count}, ${b.is_open}, ${b.is_featured}, ${b.is_premium}, ${b.is_lgbt_friendly}, ${esc(b.tags)}, ${esc(b.photos)})`
  try {
    await query(sql)
    process.stdout.write('✓ ' + b.name + '\n')
    inserted++
  } catch (e) {
    process.stdout.write('✗ ' + b.name + ': ' + e.message.slice(0, 100) + '\n')
    failed++
  }
}
console.log('\nDone! ' + inserted + ' inserted, ' + failed + ' failed.')
