import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL,
  'process.env.SUPABASE_SERVICE_KEY'
)

// ─── LISTINGS ───────────────────────────────────────────────
const listings = [
  // RESTAURANTS
  { name: 'Café des Artistes', category: 'Restaurants', neighborhood: 'Centro', address: 'Guadalupe Sánchez 740, Centro, Puerto Vallarta', latitude: 20.6055, longitude: -105.2368, description: "Puerto Vallarta's most celebrated fine-dining restaurant, open 35+ years. Chef Thierry Blouet transforms ingredients into culinary art inside a stunning colonial mansion. Smart casual — children 8+ only.", photos: ['fork.knife'], rating: 4.8, review_count: 7377, price_range: 4, phone: '+52 322 226 7200', website: 'https://cafedesartistes.com', instagram: '@cafedeartistes', tags: ['Fine Dining','French-Mexican Fusion','Romantic','Award-Winning','Wine List'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Mon–Sun 4:00 PM – 12:00 AM', is_lgbt_friendly: false },
  { name: 'Tuna Azul', category: 'Restaurants', neighborhood: 'Zona Romántica', address: 'Rodolfo Gómez 109, Col. E. Zapata, Puerto Vallarta', latitude: 20.5983, longitude: -105.2371, description: '#1 on TripAdvisor Puerto Vallarta. Family-run gem serving fresh tuna aguachile, marlin al pastor, and octopus chicharrón. Tiny space, huge flavor — arrive early.', photos: ['fork.knife'], rating: 4.9, review_count: 2865, price_range: 2, phone: '+52 322 222 0795', website: null, instagram: '@tunaazulpv', tags: ['Seafood','Fresh Tuna','Local Favorite','Authentic Mexican','Casual'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Tue–Sun 11:00 AM – 6:00 PM', is_lgbt_friendly: true },
  { name: 'La Palapa', category: 'Restaurants', neighborhood: 'Zona Romántica', address: 'Pulpito 103, Playa Los Muertos, Puerto Vallarta', latitude: 20.5971, longitude: -105.2397, description: 'Iconic beachfront restaurant on Los Muertos Beach since 1959. Fresh Pacific seafood, tropical cocktails, and legendary breakfasts with your feet in the sand.', photos: ['fork.knife'], rating: 4.5, review_count: 7272, price_range: 2, phone: '+52 322 222 5225', website: 'https://lapalapapv.com', instagram: '@lapalapapv', tags: ['Beachfront','Seafood','Breakfast','Brunch','Iconic','Tropical'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 8:00 AM – 11:00 PM', is_lgbt_friendly: true },
  { name: 'Mar Y Vino', category: 'Restaurants', neighborhood: 'Hotel Zone', address: 'Paseo de la Marina Sur 220, Marina Vallarta, Puerto Vallarta', latitude: 20.6658, longitude: -105.2598, description: 'Clifftop restaurant with sweeping panoramic views of Banderas Bay. Contemporary Mexican cuisine and an outstanding wine list. Perfect for sunsets.', photos: ['fork.knife'], rating: 4.8, review_count: 2172, price_range: 3, phone: '+52 322 221 0722', website: 'https://maryvino.com', instagram: '@maryvino_pv', tags: ['Panoramic Views','Sunset','Mexican','Wine','Romantic','Seafood'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Mon–Sun 1:00 PM – 11:00 PM', is_lgbt_friendly: false },
  { name: 'Barcelona Tapas', category: 'Restaurants', neighborhood: 'Centro', address: 'Morelos 531, Centro, Puerto Vallarta', latitude: 20.6060, longitude: -105.2345, description: "Puerto Vallarta's beloved Spanish tapas bar with 3,300+ reviews. Authentic patatas bravas, jamón ibérico, seafood croquetas, paella, and incredible sangria on the Malecon.", photos: ['fork.knife'], rating: 4.7, review_count: 3302, price_range: 2, phone: '+52 322 222 0510', website: 'https://barcelonatapas.net', instagram: '@barcelonatapas_pv', tags: ['Spanish','Tapas','Sangria','Paella','Malecon','Late Night'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Mon–Sun 12:00 PM – 1:00 AM', is_lgbt_friendly: false },

  // BARS & NIGHTLIFE
  { name: 'Los Muertos Brewing', category: 'Bars & Nightlife', neighborhood: 'Zona Romántica', address: 'Lázaro Cárdenas 302, Zona Romántica, Puerto Vallarta', latitude: 20.5985, longitude: -105.2378, description: "Puerto Vallarta's first craft brewery. Tropical-inspired beers brewed on-site, lively rooftop terrace with ocean views.", photos: ['music.note'], rating: 4.7, review_count: 521, price_range: 2, phone: '+52 322 222 6516', website: null, instagram: null, tags: ['Craft Beer','Rooftop','LGBT Friendly','Live Music'], is_premium: true, is_featured: true, is_open: true, open_hours: '2:00 PM – 1:00 AM', is_lgbt_friendly: true },
  { name: 'Mandala Beach Club', category: 'Bars & Nightlife', neighborhood: 'Hotel Zone', address: 'Blvd. Francisco Medina Ascencio, Hotel Zone, Puerto Vallarta', latitude: 20.6350, longitude: -105.2410, description: "Puerto Vallarta's hottest beach club and nightclub. International DJs, bottle service, swim-up bar.", photos: ['music.note'], rating: 4.4, review_count: 897, price_range: 3, phone: null, website: null, instagram: null, tags: ['Club','Beach Club','DJ','Party'], is_premium: true, is_featured: true, is_open: false, open_hours: '10:00 PM – 5:00 AM', is_lgbt_friendly: false },
  { name: 'La Noche Bar', category: 'Bars & Nightlife', neighborhood: 'Zona Romántica', address: 'Lázaro Cárdenas 257, Zona Romántica, Puerto Vallarta', latitude: 20.5982, longitude: -105.2375, description: 'Beloved LGBT+ bar in the heart of Zona Romántica. Weekly drag shows, theme nights, and the friendliest staff in PV.', photos: ['music.note'], rating: 4.8, review_count: 443, price_range: 2, phone: null, website: null, instagram: '@lanochepv', tags: ['LGBT+','Drag Shows','Gay Bar','Fun'], is_premium: false, is_featured: true, is_open: true, open_hours: '6:00 PM – 3:00 AM', is_lgbt_friendly: true },

  // HOTELS
  { name: 'Garza Blanca Preserve Resort & Spa', category: 'Hotels', neighborhood: 'Hotel Zone', address: 'Carr. Barra de Navidad Km 7.5, Puerto Vallarta', latitude: 20.5610, longitude: -105.2570, description: 'Ultra-luxury 5-star resort with private beach, multiple pools, gourmet restaurants, and world-class spa.', photos: ['bed.double.fill'], rating: 4.9, review_count: 1876, price_range: 4, phone: '+52 322 176 0700', website: 'https://garzablanca.com', instagram: null, tags: ['5-Star','Luxury','Spa','Private Beach','All-Inclusive Option'], is_premium: true, is_featured: true, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },
  { name: 'Casa Kimberly', category: 'Hotels', neighborhood: 'Centro', address: 'Zaragoza 445, Centro, Puerto Vallarta', latitude: 20.6048, longitude: -105.2360, description: 'The legendary former home of Elizabeth Taylor & Richard Burton, converted into a stunning boutique luxury hotel.', photos: ['bed.double.fill'], rating: 4.8, review_count: 634, price_range: 4, phone: '+52 322 222 1336', website: 'https://casakimberly.com', instagram: null, tags: ['Boutique','Historic','Romantic','Views','Adults Only'], is_premium: true, is_featured: true, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },
  { name: 'W Punta de Mita', category: 'Hotels', neighborhood: 'Punta Mita', address: 'Lote H-1, Corral del Risco, Punta de Mita, Nayarit', latitude: 20.7715, longitude: -105.4970, description: 'Ultra-cool luxury resort in Punta Mita. Celebrity hotspot with stunning beach, W Lounge, and insane pool scene.', photos: ['bed.double.fill'], rating: 4.7, review_count: 912, price_range: 4, phone: null, website: null, instagram: null, tags: ['5-Star','Beach','Pool','Celebrity','Surfing'], is_premium: true, is_featured: false, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },

  // ACTIVITIES
  { name: 'Marietas Islands Snorkeling & Hidden Beach', category: 'Activities', neighborhood: 'Punta Mita', address: 'Departs from La Cruz Marina, Nayarit', latitude: 20.7130, longitude: -105.5600, description: 'Iconic tour to the Marieta Islands — a UNESCO protected area. Snorkel with sea turtles, manta rays, and visit the famous Hidden Beach.', photos: ['figure.surfing'], rating: 4.9, review_count: 2341, price_range: 2, phone: '+52 322 297 1212', website: null, instagram: null, tags: ['Snorkeling','Wildlife','UNESCO','Hidden Beach','Day Trip'], is_premium: false, is_featured: true, is_open: true, open_hours: '8:00 AM – 5:00 PM', is_lgbt_friendly: false },
  { name: 'Canopy River Zip-line & ATV', category: 'Activities', neighborhood: 'Centro', address: 'Carr. a Boca de Tomatlán Km 3, Puerto Vallarta', latitude: 20.5720, longitude: -105.2490, description: 'Thrilling zip-line tour through the jungle canopy above the Cuale River. Combine with ATV adventure and a traditional Mexican lunch.', photos: ['figure.surfing'], rating: 4.7, review_count: 1564, price_range: 3, phone: '+52 322 222 4330', website: null, instagram: null, tags: ['Zip-line','ATV','Jungle','Adventure','Family'], is_premium: true, is_featured: true, is_open: true, open_hours: '8:00 AM – 5:00 PM', is_lgbt_friendly: false },
  { name: 'Whale Watching PV', category: 'Activities', neighborhood: 'Marina', address: 'Departs from Marina Vallarta', latitude: 20.6720, longitude: -105.2540, description: "Seasonal humpback whale watching tours Nov–Mar. Banderas Bay is one of the world's best spots to see humpback whales up close.", photos: ['figure.surfing'], rating: 4.9, review_count: 876, price_range: 2, phone: null, website: null, instagram: null, tags: ['Whale Watching','Seasonal','Wildlife','Ocean','Photography'], is_premium: false, is_featured: true, is_open: false, open_hours: 'Nov–Mar: 8:00 AM – 1:00 PM', is_lgbt_friendly: false },
  { name: 'Sayulita Surf School', category: 'Activities', neighborhood: 'Sayulita', address: 'Playa Sayulita, Sayulita, Nayarit', latitude: 20.8690, longitude: -105.4460, description: "Learn to surf in one of Mexico's most famous surf towns. Beginners to advanced lessons, board rentals, daily surf camps.", photos: ['figure.surfing'], rating: 4.8, review_count: 445, price_range: 2, phone: null, website: null, instagram: '@sayulitasurf', tags: ['Surfing','Lessons','Beginner','Sayulita','Beach'], is_premium: false, is_featured: true, is_open: true, open_hours: '7:00 AM – 6:00 PM', is_lgbt_friendly: false },

  // YACHT RENTALS
  { name: 'Sunset Sailing Cruise PV', category: 'Yacht Rentals', neighborhood: 'Marina', address: 'Marina Vallarta, Dock B, Puerto Vallarta', latitude: 20.6715, longitude: -105.2545, description: '4-hour sunset sailing cruise aboard a 42ft catamaran. Open bar, snorkeling stop, live music. The most romantic experience in Puerto Vallarta.', photos: ['sailboat.fill'], rating: 4.9, review_count: 1123, price_range: 3, phone: '+52 322 225 4777', website: null, instagram: null, tags: ['Sunset','Catamaran','Open Bar','Snorkeling','Romantic'], is_premium: true, is_featured: true, is_open: true, open_hours: '3:00 PM – 7:00 PM', is_lgbt_friendly: true },
  { name: 'Private Yacht Charter — Marietas', category: 'Yacht Rentals', neighborhood: 'Marina', address: 'Marina Vallarta, Puerto Vallarta', latitude: 20.6718, longitude: -105.2548, description: 'Full-day private yacht charter to the Marieta Islands. Up to 12 guests. Captain, crew, gourmet catering, snorkel gear, paddleboards.', photos: ['sailboat.fill'], rating: 4.8, review_count: 312, price_range: 4, phone: '+52 322 225 5000', website: null, instagram: null, tags: ['Private','Charter','Full Day','Luxury','Snorkeling'], is_premium: true, is_featured: false, is_open: true, open_hours: '8:00 AM – 6:00 PM', is_lgbt_friendly: false },

  // CAR & MOTO RENTAL
  { name: 'Vallarta Car Rental', category: 'Car & Moto Rental', neighborhood: 'Centro', address: 'Blvd. Francisco Medina Ascencio 1728, Puerto Vallarta', latitude: 20.6320, longitude: -105.2430, description: 'Best rates on car rentals in Puerto Vallarta. Large fleet: economy cars, SUVs, convertibles. Airport pickup available.', photos: ['car.fill'], rating: 4.5, review_count: 678, price_range: 2, phone: '+52 322 222 0999', website: null, instagram: null, tags: ['Car Rental','Airport','SUV','Economy','Convertible'], is_premium: true, is_featured: false, is_open: true, open_hours: '8:00 AM – 8:00 PM', is_lgbt_friendly: false },
  { name: 'Moto Rent PV', category: 'Car & Moto Rental', neighborhood: 'Zona Romántica', address: 'Olas Altas 390, Zona Romántica, Puerto Vallarta', latitude: 20.5988, longitude: -105.2371, description: 'Scooters, motorbikes, and ATVs for rent by the hour or day. Explore PV on two wheels. Helmets and insurance included.', photos: ['car.fill'], rating: 4.6, review_count: 289, price_range: 1, phone: '+52 322 222 1234', website: null, instagram: '@motorentpv', tags: ['Moto','Scooter','ATV','Hourly','Daily'], is_premium: false, is_featured: false, is_open: true, open_hours: '9:00 AM – 7:00 PM', is_lgbt_friendly: false },

  // BEACHES
  { name: 'Playa Los Muertos', category: 'Beaches', neighborhood: 'Zona Romántica', address: 'Playa Los Muertos, Zona Romántica, Puerto Vallarta', latitude: 20.5970, longitude: -105.2400, description: "Puerto Vallarta's most famous beach. Gay-friendly south end (Blue Chairs), beach restaurants, volleyball, parasailing, and legendary sunsets.", photos: ['sun.max.fill'], rating: 4.8, review_count: 4521, price_range: 0, phone: null, website: null, instagram: null, tags: ['Gay Friendly','Beach Bars','Sunset','Volleyball','Central'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Always open', is_lgbt_friendly: true },
  { name: 'Playa Sayulita', category: 'Beaches', neighborhood: 'Sayulita', address: 'Sayulita, Nayarit', latitude: 20.8685, longitude: -105.4458, description: 'Charming bohemian surf beach in Sayulita. Mexican fishermen, surfers, and hippie travelers all coexist. Colorful town, great tacos nearby.', photos: ['sun.max.fill'], rating: 4.7, review_count: 2134, price_range: 0, phone: null, website: null, instagram: null, tags: ['Surf','Bohemian','Town','Colorful','Fishing'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Always open', is_lgbt_friendly: false },

  // SHOPPING
  { name: 'Mercado de Artesanías', category: 'Shopping', neighborhood: 'Centro', address: 'Agustín Rodríguez 164, Centro, Puerto Vallarta', latitude: 20.6042, longitude: -105.2348, description: "Puerto Vallarta's famous artisan market. Huichol beadwork, Talavera ceramics, handwoven textiles, leather goods, and silver jewelry.", photos: ['bag.fill'], rating: 4.5, review_count: 1872, price_range: 1, phone: null, website: null, instagram: null, tags: ['Artisan','Souvenirs','Huichol','Handmade','Market'], is_premium: false, is_featured: true, is_open: true, open_hours: '9:00 AM – 8:00 PM', is_lgbt_friendly: false },

  // SPAS & WELLNESS
  { name: 'Garza Blanca Spa', category: 'Spas & Wellness', neighborhood: 'Hotel Zone', address: 'Carr. Barra de Navidad Km 7.5, Puerto Vallarta', latitude: 20.5612, longitude: -105.2572, description: 'World-class spa at Garza Blanca Resort. Signature treatments inspired by Mexican healing traditions. Ocean views, hydrotherapy, couples suites.', photos: ['leaf.fill'], rating: 4.9, review_count: 456, price_range: 4, phone: '+52 322 176 0700', website: null, instagram: null, tags: ['Luxury Spa','Couples','Hydrotherapy','Ocean Views','Massage'], is_premium: true, is_featured: true, is_open: true, open_hours: '9:00 AM – 9:00 PM', is_lgbt_friendly: false },
]

// ─── EVENTS ─────────────────────────────────────────────────
const now = new Date()
const daysFromNow = (d, h = 20) => {
  const date = new Date(now)
  date.setDate(date.getDate() + d)
  date.setHours(h, 0, 0, 0)
  return date.toISOString()
}

const events = [
  { title: 'Vallarta Pride 2026', description: "Puerto Vallarta's world-famous Pride festival. Week-long celebration with parades, concerts, beach parties, and the iconic parade along the Malecón.", neighborhood: 'Zona Romántica', address: 'Zona Romántica & Malecón, Puerto Vallarta', latitude: 20.5985, longitude: -105.2380, start_date: daysFromNow(14, 12), end_date: daysFromNow(21, 23), is_public: true, is_free: true, ticket_price: null, ticket_url: null, photos: ['calendar'], tags: ['Pride','LGBT+','Parade','Festival','Annual'], organizer: 'Vallarta Pride Organization', instagram: '@vallartapride', is_premium: false, is_featured: true, is_lgbt_friendly: true, is_recurring: true, recurrence_label: 'Annual' },
  { title: 'Moonlight Jazz at the Marina', description: "Exclusive monthly jazz evening at Marina Vallarta's premier yacht club. Live jazz quartet, gourmet tapas, craft cocktails under the stars.", neighborhood: 'Marina', address: 'Yacht Club Marina Vallarta, Puerto Vallarta', latitude: 20.6715, longitude: -105.2545, start_date: daysFromNow(3, 19), end_date: daysFromNow(3, 23), is_public: false, is_free: false, ticket_price: 850, ticket_url: null, photos: ['calendar'], tags: ['Jazz','Live Music','Cocktails','Exclusive','Marina'], organizer: 'Marina Yacht Club', instagram: null, is_premium: true, is_featured: true, is_lgbt_friendly: false, is_recurring: true, recurrence_label: 'Monthly' },
  { title: 'Sayulita Surf Competition', description: 'Annual amateur and pro surf competition at Playa Sayulita. Free entry for spectators, food and craft vendors on the beach.', neighborhood: 'Sayulita', address: 'Playa Sayulita, Nayarit', latitude: 20.8685, longitude: -105.4458, start_date: daysFromNow(7, 8), end_date: daysFromNow(9, 18), is_public: true, is_free: true, ticket_price: null, ticket_url: null, photos: ['calendar'], tags: ['Surf','Competition','Sayulita','Sport','Annual'], organizer: 'Sayulita Surf Club', instagram: null, is_premium: false, is_featured: true, is_lgbt_friendly: false, is_recurring: true, recurrence_label: 'Annual' },
  { title: 'Gourmet Food & Wine Festival', description: "Puerto Vallarta's renowned Gourmet Festival. 10 days of special menus, wine pairings, and culinary events at 50+ top restaurants.", neighborhood: 'Centro', address: 'Multiple venues, Puerto Vallarta', latitude: 20.6060, longitude: -105.2370, start_date: daysFromNow(30, 12), end_date: daysFromNow(40, 23), is_public: true, is_free: false, ticket_price: 500, ticket_url: null, photos: ['calendar'], tags: ['Gourmet','Wine','Restaurants','Festival','Annual'], organizer: 'Festival Gourmet Internacional', instagram: null, is_premium: false, is_featured: true, is_lgbt_friendly: false, is_recurring: true, recurrence_label: 'Annual - November' },
  { title: 'Thursday Night Art Walk', description: "Every Thursday the Centro galleries open late. Meet local and international artists, enjoy wine, discover PV's thriving art scene.", neighborhood: 'Centro', address: 'Zona Centro — start at Galería Dante, Puerto Vallarta', latitude: 20.6050, longitude: -105.2355, start_date: daysFromNow(4, 18), end_date: daysFromNow(4, 22), is_public: true, is_free: true, ticket_price: null, ticket_url: null, photos: ['calendar'], tags: ['Art','Galleries','Culture','Wine','Weekly'], organizer: 'PV Art Galleries Association', instagram: null, is_premium: false, is_featured: true, is_lgbt_friendly: false, is_recurring: true, recurrence_label: 'Every Thursday' },
  { title: 'Sunset Beach Party — Blue Chairs', description: 'The legendary daily sunset party at Blue Chairs Resort on Los Muertos Beach. DJs, dancers, signature cocktails, best sunset view in town.', neighborhood: 'Zona Romántica', address: 'Blue Chairs Resort, Playa Los Muertos, Puerto Vallarta', latitude: 20.5968, longitude: -105.2398, start_date: daysFromNow(1, 17), end_date: daysFromNow(1, 21), is_public: true, is_free: true, ticket_price: null, ticket_url: null, photos: ['calendar'], tags: ['Sunset','DJ','Beach','LGBT+','Daily'], organizer: 'Blue Chairs Resort', instagram: null, is_premium: false, is_featured: true, is_lgbt_friendly: true, is_recurring: true, recurrence_label: 'Daily' },
]

// ─── SEED ────────────────────────────────────────────────────
async function seed() {
  console.log('🗑️  Clearing existing data...')

  const { error: delListings } = await supabase.from('listings').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  if (delListings) console.error('Error clearing listings:', delListings.message)

  const { error: delEvents } = await supabase.from('events').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  if (delEvents) console.error('Error clearing events:', delEvents.message)

  console.log('📦 Inserting listings...')
  const { error: listErr } = await supabase.from('listings').insert(listings)
  if (listErr) {
    console.error('❌ Listings error:', listErr.message)
    process.exit(1)
  }
  console.log(`✅ ${listings.length} listings inserted`)

  console.log('📅 Inserting events...')
  const { error: evtErr } = await supabase.from('events').insert(events)
  if (evtErr) {
    console.error('❌ Events error:', evtErr.message)
    process.exit(1)
  }
  console.log(`✅ ${events.length} events inserted`)

  // Verify
  const { data: listCount } = await supabase.from('listings').select('id', { count: 'exact', head: true })
  const { count: lCount } = await supabase.from('listings').select('*', { count: 'exact', head: true })
  const { count: eCount } = await supabase.from('events').select('*', { count: 'exact', head: true })
  console.log(`\n🎉 Done! ${lCount} listings | ${eCount} events in Supabase`)
  console.log('👉 Kill and relaunch the app in the simulator to see live data')
}

seed()
