import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
)

const listings = [
  // RESTAURANTS (8)
  { name: 'Café des Artistes', category: 'Restaurants', neighborhood: 'Centro', address: 'Guadalupe Sánchez 740, Centro, Puerto Vallarta', latitude: 20.6055, longitude: -105.2368, description: "Puerto Vallarta's most celebrated fine-dining restaurant. Chef Thierry Blouet transforms local ingredients into culinary art inside a stunning colonial mansion. Smart casual, children 8+ only.", photos: [], rating: 4.8, review_count: 7381, price_range: 4, phone: '+52 322 226 7200', website: 'https://cafedesartistes.com', instagram: '@cafedeartistes', tags: ['Fine Dining','French-Mexican Fusion','Romantic','Award-Winning','Wine List'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Mon–Sun 4:00 PM – 12:00 AM', is_lgbt_friendly: false },
  { name: 'Tuna Azul', category: 'Restaurants', neighborhood: 'Zona Romántica', address: 'Rodolfo Gómez 109, Col. E. Zapata, Puerto Vallarta', latitude: 20.5983, longitude: -105.2371, description: '#1 rated restaurant in Puerto Vallarta. Family-run gem serving fresh tuna aguachile, marlin al pastor, and octopus chicharrón. Tiny space, huge flavor.', photos: [], rating: 4.9, review_count: 2900, price_range: 2, phone: '+52 322 222 0795', website: null, instagram: '@tunaazulpv', tags: ['Seafood','Fresh Tuna','Local Favorite','Authentic Mexican','Casual'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Tue–Sun 11:00 AM – 6:00 PM', is_lgbt_friendly: true },
  { name: 'La Palapa', category: 'Restaurants', neighborhood: 'Zona Romántica', address: 'Pulpito 103, Playa Los Muertos, Puerto Vallarta', latitude: 20.5971, longitude: -105.2397, description: 'Iconic beachfront restaurant on Los Muertos Beach since 1959. Fresh Pacific seafood, tropical cocktails, and legendary breakfasts with your feet in the sand.', photos: [], rating: 4.5, review_count: 7272, price_range: 2, phone: '+52 322 222 5225', website: 'https://lapalapapv.com', instagram: '@lapalapapv', tags: ['Beachfront','Seafood','Breakfast','Brunch','Iconic','Tropical'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 8:00 AM – 11:00 PM', is_lgbt_friendly: true },
  { name: 'Mar Y Vino', category: 'Restaurants', neighborhood: 'Zona Romántica', address: 'Manuel M. Diéguez 106, Col. E. Zapata, Puerto Vallarta', latitude: 20.5988, longitude: -105.2373, description: 'Contemporary Mexican cuisine with an outstanding wine list and panoramic views of Banderas Bay. The tuna and octopus are legendary. Perfect for sunset dinners.', photos: [], rating: 4.8, review_count: 2184, price_range: 3, phone: '+52 322 221 0722', website: 'https://maryvino.com', instagram: '@maryvino_pv', tags: ['Panoramic Views','Sunset','Mexican','Wine','Romantic','Seafood'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Mon–Sun 1:00 PM – 11:00 PM', is_lgbt_friendly: false },
  { name: 'Barcelona Tapas', category: 'Restaurants', neighborhood: 'Centro', address: 'Morelos 531, Centro, Puerto Vallarta', latitude: 20.6060, longitude: -105.2345, description: "Puerto Vallarta's beloved Spanish tapas bar. Authentic patatas bravas, jamón ibérico, seafood croquetas, paella, and incredible sangria on the Malecon.", photos: [], rating: 4.7, review_count: 3303, price_range: 2, phone: '+52 322 222 0510', website: 'https://barcelonatapas.net', instagram: '@barcelonatapas_pv', tags: ['Spanish','Tapas','Sangria','Paella','Malecon','Late Night'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Mon–Sun 12:00 PM – 1:00 AM', is_lgbt_friendly: false },
  { name: 'El Dorado Restaurant', category: 'Restaurants', neighborhood: 'Zona Romántica', address: 'Pulpito 102, Playa Los Muertos, Puerto Vallarta', latitude: 20.5969, longitude: -105.2398, description: 'Beachfront fine dining at its best. Fresh catch of the day, seared ahi tuna, and organic chicken on the beach at Los Muertos. Romantic atmosphere with live jazz.', photos: [], rating: 4.6, review_count: 1627, price_range: 3, phone: '+52 322 222 1511', website: 'https://eldoradopvr.com', instagram: '@eldoradopv', tags: ['Beachfront','Fine Dining','Seafood','Jazz','Romantic'], is_premium: true, is_featured: false, is_open: true, open_hours: 'Daily 9:00 AM – 11:00 PM', is_lgbt_friendly: true },
  { name: 'Café San Angel', category: 'Restaurants', neighborhood: 'Zona Romántica', address: 'Olas Altas 449, Zona Romántica, Puerto Vallarta', latitude: 20.5994, longitude: -105.2378, description: "Casual sidewalk cafe serving one of PV's best burgers, al pastor tacos, and fresh-squeezed juices. Great spot to people-watch all day.", photos: [], rating: 4.7, review_count: 1825, price_range: 2, phone: '+52 322 223 1273', website: null, instagram: '@cafesanangelpv', tags: ['Casual','Burgers','Tacos','Sidewalk','Breakfast','Lunch'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 8:00 AM – 11:00 PM', is_lgbt_friendly: true },
  { name: 'Noroc', category: 'Restaurants', neighborhood: 'Centro', address: 'Galeana 225, Centro, Puerto Vallarta', latitude: 20.6053, longitude: -105.2352, description: 'Trendy upscale restaurant serving lamb, short rib, lobster, octopus, and tortellini. Intimate space with creative presentations and an exceptional cocktail menu.', photos: [], rating: 4.8, review_count: 1265, price_range: 4, phone: '+52 322 136 6547', website: null, instagram: '@norocpv', tags: ['Contemporary','Lamb','Lobster','Cocktails','Intimate'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Tue–Sun 5:00 PM – 11:00 PM', is_lgbt_friendly: false },

  // BARS & NIGHTLIFE (7)
  { name: 'Los Muertos Brewing', category: 'Bars & Nightlife', neighborhood: 'Zona Romántica', address: 'Lázaro Cárdenas 302, Zona Romántica, Puerto Vallarta', latitude: 20.5985, longitude: -105.2378, description: "Puerto Vallarta's first craft brewery. Tropical-inspired beers brewed on-site, lively rooftop terrace with ocean views.", photos: [], rating: 4.7, review_count: 521, price_range: 2, phone: '+52 322 222 6516', website: 'https://losmuertosbrewing.com', instagram: '@losmuertosbrewing', tags: ['Craft Beer','Rooftop','LGBT Friendly','Live Music','Local Brewery'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 2:00 PM – 1:00 AM', is_lgbt_friendly: true },
  { name: 'La Noche Bar', category: 'Bars & Nightlife', neighborhood: 'Zona Romántica', address: 'Lázaro Cárdenas 257, Zona Romántica, Puerto Vallarta', latitude: 20.5982, longitude: -105.2375, description: 'Beloved LGBT+ bar in the heart of Zona Romántica. Weekly drag shows, theme nights, and the friendliest staff in PV. Dancing until 3am every night.', photos: [], rating: 4.8, review_count: 443, price_range: 2, phone: null, website: null, instagram: '@lanochepv', tags: ['LGBT+','Drag Shows','Gay Bar','Dancing','Fun'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Daily 6:00 PM – 3:00 AM', is_lgbt_friendly: true },
  { name: 'Mandala Nightclub', category: 'Bars & Nightlife', neighborhood: 'Centro', address: 'Paseo Díaz Ordaz 633, Centro, Puerto Vallarta', latitude: 20.6052, longitude: -105.2340, description: "Puerto Vallarta's hottest nightclub on the Malecón. International DJs, laser shows, bottle service, and multiple dance floors. The place to be after midnight.", photos: [], rating: 4.4, review_count: 897, price_range: 3, phone: null, website: 'https://mandala.com.mx', instagram: '@mandalapv', tags: ['Nightclub','DJ','Laser Show','Bottle Service','Malecon'], is_premium: true, is_featured: true, is_open: false, open_hours: 'Thu–Sat 10:00 PM – 5:00 AM', is_lgbt_friendly: false },
  { name: 'The Top Sky Bar', category: 'Bars & Nightlife', neighborhood: 'Hotel Zone', address: 'Av. México 1301, Hotel Zone, Puerto Vallarta', latitude: 20.6280, longitude: -105.2400, description: "Puerto Vallarta's best rooftop bar with 360-degree views of the bay, mountains, and city. Incredible sunsets, creative cocktails, and live DJ on weekends.", photos: [], rating: 4.8, review_count: 733, price_range: 3, phone: '+52 322 226 7000', website: 'https://almarresort.com/thetop', instagram: '@thetoppv', tags: ['Rooftop','Views','Cocktails','Sunset','DJ','Hotel Bar'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 4:00 PM – 1:00 AM', is_lgbt_friendly: false },
  { name: 'iK Mixology Bar & Cuisine', category: 'Bars & Nightlife', neighborhood: 'Centro', address: 'Juárez 476, Centro, Puerto Vallarta', latitude: 20.6045, longitude: -105.2358, description: 'Sophisticated cocktail bar serving creative mixology with fresh local ingredients. Small plates menu pairs perfectly with their signature mezcal cocktails.', photos: [], rating: 4.8, review_count: 719, price_range: 3, phone: '+52 322 222 3380', website: null, instagram: '@ikmixologypv', tags: ['Cocktails','Mezcal','Mixology','Small Plates','Chic'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Tue–Sun 5:00 PM – 1:00 AM', is_lgbt_friendly: false },
  { name: 'Blue Chairs Beach Club', category: 'Bars & Nightlife', neighborhood: 'Zona Romántica', address: 'Olas Altas 392, Playa Los Muertos, Puerto Vallarta', latitude: 20.5975, longitude: -105.2395, description: "The legendary LGBT+ beach club at the south end of Los Muertos Beach. Day beds, cocktails, drag shows on the sand, and the most fun crowd in PV.", photos: [], rating: 4.6, review_count: 1284, price_range: 2, phone: '+52 322 222 5040', website: 'https://bluechairs.com', instagram: '@bluechairspv', tags: ['LGBT+','Beach Club','Day Beds','Drag Shows','Gay Beach'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Daily 9:00 AM – 10:00 PM', is_lgbt_friendly: true },
  { name: "Andale's Restaurant & Bar", category: 'Bars & Nightlife', neighborhood: 'Zona Romántica', address: 'Olas Altas 425, Zona Romántica, Puerto Vallarta', latitude: 20.5991, longitude: -105.2380, description: "PV institution since 1978. Cold beers, margaritas, fajitas, and great people-watching on the Olas Altas strip.", photos: [], rating: 4.5, review_count: 1419, price_range: 2, phone: '+52 322 222 1054', website: 'https://andalesrestaurant.com', instagram: '@andalespv', tags: ['Classic Bar','Margaritas','Fajitas','Late Night','Institution'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 10:00 AM – 2:00 AM', is_lgbt_friendly: true },

  // HOTELS (7)
  { name: 'Garza Blanca Preserve Resort & Spa', category: 'Hotels', neighborhood: 'Hotel Zone', address: 'Carr. Barra de Navidad Km 7.5, Puerto Vallarta', latitude: 20.5610, longitude: -105.2570, description: 'Ultra-luxury 5-star resort with private beach, multiple pools, gourmet restaurants, and world-class spa. Cliffside villas with stunning ocean views.', photos: [], rating: 4.9, review_count: 1876, price_range: 4, phone: '+52 322 176 0700', website: 'https://garzablanca.com', instagram: '@garzablancapv', tags: ['5-Star','Luxury','Spa','Private Beach','Pool Villas'], is_premium: true, is_featured: true, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },
  { name: 'Casa Kimberly', category: 'Hotels', neighborhood: 'Centro', address: 'Zaragoza 445, Centro, Puerto Vallarta', latitude: 20.6048, longitude: -105.2360, description: "The legendary former home of Elizabeth Taylor and Richard Burton. The famous pink bridge connecting the two houses is iconic. Stunning boutique luxury hotel.", photos: [], rating: 4.8, review_count: 634, price_range: 4, phone: '+52 322 222 1336', website: 'https://casakimberly.com', instagram: '@casakimberly', tags: ['Boutique','Historic','Romantic','Views','Adults Only','Elizabeth Taylor'], is_premium: true, is_featured: true, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },
  { name: 'W Punta de Mita', category: 'Hotels', neighborhood: 'Punta Mita', address: 'Lote H-1, Corral del Risco, Punta de Mita, Nayarit', latitude: 20.7715, longitude: -105.4970, description: 'Ultra-cool 5-star resort in Punta Mita. Celebrity hotspot with stunning beach, W Lounge, and legendary pool scene. 30 minutes from PV.', photos: [], rating: 4.7, review_count: 912, price_range: 4, phone: null, website: 'https://marriott.com/en-us/hotels/pvrzw-w-punta-de-mita', instagram: '@wpuntademita', tags: ['5-Star','Beach','Pool','Celebrity','Surfing','Punta Mita'], is_premium: true, is_featured: false, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },
  { name: 'Hotel Mousai', category: 'Hotels', neighborhood: 'Hotel Zone', address: 'Carr. Barra de Navidad Km 7.5, Puerto Vallarta', latitude: 20.5608, longitude: -105.2568, description: 'Adults-only luxury boutique hotel perched above the Pacific. Swim-up suites, rooftop pool, world-class dining. No children under 18.', photos: [], rating: 4.9, review_count: 987, price_range: 4, phone: '+52 322 176 0700', website: 'https://hotelmousai.com', instagram: '@hotelmousai', tags: ['Adults Only','Swim-Up Suites','Rooftop','Luxury','Boutique'], is_premium: true, is_featured: true, is_open: true, open_hours: '24 hours', is_lgbt_friendly: true },
  { name: 'Hacienda San Angel', category: 'Hotels', neighborhood: 'Centro', address: 'Miramar 336, Centro, Puerto Vallarta', latitude: 20.6073, longitude: -105.2335, description: 'Romantic boutique hotel in historic hillside colonial mansions. Once home to Richard Burton. Spectacular bay views, rooftop terrace, and pool with sunset views.', photos: [], rating: 4.9, review_count: 567, price_range: 4, phone: '+52 322 222 2692', website: 'https://haciendasanangel.com', instagram: '@haciendasa', tags: ['Boutique','Historic','Romantic','Richard Burton','Views','Colonial'], is_premium: true, is_featured: true, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },
  { name: 'Hilton Vallarta Riviera', category: 'Hotels', neighborhood: 'Hotel Zone', address: 'Blvd. Francisco Medina Ascencio 4205, Hotel Zone, Puerto Vallarta', latitude: 20.6498, longitude: -105.2430, description: 'All-inclusive beachfront resort with multiple pools, 7 restaurants and bars, full spa, and direct beach access. Great for families and groups.', photos: [], rating: 4.6, review_count: 2341, price_range: 3, phone: '+52 322 176 3100', website: 'https://hilton.com', instagram: '@hiltonvallarta', tags: ['All-Inclusive','Family','Beach','Pool','Multiple Restaurants'], is_premium: false, is_featured: false, is_open: true, open_hours: '24 hours', is_lgbt_friendly: false },
  { name: 'Hotel Encanto', category: 'Hotels', neighborhood: 'Centro', address: 'Miramar 450, Centro, Puerto Vallarta', latitude: 20.6081, longitude: -105.2330, description: 'Adults-only boutique hotel in the hills above Centro. Stunning panoramic bay views from every room, infinity pool, and personalized service.', photos: [], rating: 4.7, review_count: 445, price_range: 3, phone: '+52 322 222 0400', website: 'https://encantopv.com', instagram: '@encantopv', tags: ['Adults Only','Views','Infinity Pool','Boutique','Walk to Malecon'], is_premium: false, is_featured: false, is_open: true, open_hours: '24 hours', is_lgbt_friendly: true },

  // ACTIVITIES (8)
  { name: 'Marietas Islands Snorkel & Hidden Beach', category: 'Activities', neighborhood: 'Punta Mita', address: 'Departs from La Cruz Marina, Nayarit', latitude: 20.7130, longitude: -105.5600, description: "UNESCO-protected Marieta Islands tour. Snorkel with sea turtles, manta rays, and blue-footed boobies. Visit the world-famous Hidden Beach accessible only by swimming through a cave.", photos: [], rating: 4.9, review_count: 2650, price_range: 2, phone: '+52 329 291 6298', website: null, instagram: '@ecoexplorerpv', tags: ['Snorkeling','UNESCO','Hidden Beach','Wildlife','Day Trip','Blue-Footed Boobies'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Tue–Sun 8:00 AM – 4:00 PM', is_lgbt_friendly: false },
  { name: 'Canopy River Zip-line & ATV', category: 'Activities', neighborhood: 'Centro', address: 'Carr. a Boca de Tomatlán Km 3, Puerto Vallarta', latitude: 20.5720, longitude: -105.2490, description: '13 zip-lines through the jungle canopy plus ATV adventure and the longest suspension bridge in Latin America. Traditional Mexican lunch included.', photos: [], rating: 4.8, review_count: 1564, price_range: 3, phone: '+52 322 222 4330', website: 'https://canopyriver.com', instagram: '@canopyriverpv', tags: ['Zip-line','ATV','Suspension Bridge','Jungle','Adventure','Family'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 8:00 AM – 5:00 PM', is_lgbt_friendly: false },
  { name: 'Whale Watching — Wildlife Connection', category: 'Activities', neighborhood: 'Marina', address: 'Departs from Marina Vallarta Pier, Puerto Vallarta', latitude: 20.6617, longitude: -105.2462, description: 'Led by professional marine biologists. See humpback whales, dolphins, and sea turtles in Banderas Bay. November to March. Conservation-focused ethical tour.', photos: [], rating: 4.9, review_count: 876, price_range: 2, phone: '+52 322 225 3774', website: 'https://wildlifeconnection.com.mx', instagram: '@wildlifeconnectionpv', tags: ['Whale Watching','Seasonal','Biologist','Conservation','Humpback'], is_premium: false, is_featured: true, is_open: false, open_hours: 'Nov–Mar: Daily 8:00 AM – 1:00 PM', is_lgbt_friendly: false },
  { name: 'Sayulita Surf School', category: 'Activities', neighborhood: 'Sayulita', address: 'Playa Sayulita, Sayulita, Nayarit', latitude: 20.8690, longitude: -105.4460, description: "Learn to surf at one of Mexico's most famous surf towns. Beginner to advanced lessons, board rentals, and daily surf camps.", photos: [], rating: 4.8, review_count: 445, price_range: 2, phone: null, website: null, instagram: '@sayulitasurf', tags: ['Surfing','Lessons','Beginner','Sayulita','Board Rental'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Daily 7:00 AM – 6:00 PM', is_lgbt_friendly: false },
  { name: 'Bioluminescence Night Tour — Los Arcos', category: 'Activities', neighborhood: 'Centro', address: 'Departs from Los Muertos Pier, Puerto Vallarta', latitude: 20.5975, longitude: -105.2403, description: 'Magical evening boat tour to Los Arcos sanctuary. Watch the sunset, then swim in glowing bioluminescent plankton in complete darkness.', photos: [], rating: 4.9, review_count: 405, price_range: 2, phone: null, website: null, instagram: '@pvbioluminescence', tags: ['Bioluminescence','Night Tour','Sunset','Swimming','Nature','Unique'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Daily 5:00 PM – 9:00 PM', is_lgbt_friendly: false },
  { name: 'Horseback Riding Sierra Madre', category: 'Activities', neighborhood: 'Centro', address: 'Carr. a Boca de Tomatlán, Puerto Vallarta', latitude: 20.5680, longitude: -105.2520, description: 'Ride through the Sierra Madre mountains, cross rivers, swim with your horse, and enjoy a traditional Mexican BBQ with unlimited margaritas and artisanal tequila tasting.', photos: [], rating: 4.9, review_count: 326, price_range: 3, phone: '+52 322 222 1341', website: null, instagram: '@pvhorseriding', tags: ['Horseback Riding','Sierra Madre','River Swimming','Tequila','BBQ','Adventure'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 8:00 AM – 4:00 PM', is_lgbt_friendly: false },
  { name: 'Los Arcos Snorkeling & Cliff Jumping', category: 'Activities', neighborhood: 'Centro', address: 'Departs from Mismaloya Beach, Puerto Vallarta', latitude: 20.5555, longitude: -105.2470, description: 'Snorkel at the Los Arcos Marine Geological Sanctuary. Combine with cliff jumping near the Night of the Iguana film set. Small groups, expert local guides.', photos: [], rating: 4.9, review_count: 246, price_range: 1, phone: null, website: null, instagram: '@losarcossnorkel', tags: ['Snorkeling','Cliff Jumping','Marine Reserve','Tropical Fish'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 9:00 AM – 2:00 PM', is_lgbt_friendly: false },
  { name: 'Butterfly Sanctuary & Museum', category: 'Activities', neighborhood: 'Centro', address: 'Av. Las Palmas 1810, Puerto Vallarta', latitude: 20.6230, longitude: -105.2340, description: 'Educational butterfly sanctuary and heritage museum. Release newly hatched butterflies, learn about 80+ species, and support conservation. Perfect for families. Open year-round.', photos: [], rating: 4.9, review_count: 403, price_range: 1, phone: '+52 322 225 2700', website: null, instagram: '@butterflypv', tags: ['Family','Educational','Butterflies','Conservation','Museum','All Ages'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Tue–Sun 10:00 AM – 5:00 PM', is_lgbt_friendly: false },

  // YACHT RENTALS (5)
  { name: 'Sunset Sailing Cruise PV', category: 'Yacht Rentals', neighborhood: 'Marina', address: 'Marina Vallarta, Dock B, Puerto Vallarta', latitude: 20.6760, longitude: -105.2580, description: '4-hour sunset sailing cruise aboard a 42ft catamaran. Open bar, snorkeling stop at Los Arcos, live music. The most romantic experience in Puerto Vallarta.', photos: [], rating: 4.9, review_count: 1123, price_range: 3, phone: '+52 322 225 4777', website: null, instagram: '@pvsunsetsailing', tags: ['Sunset','Catamaran','Open Bar','Snorkeling','Romantic','Live Music'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 3:00 PM – 7:00 PM', is_lgbt_friendly: true },
  { name: 'Private Yacht Charter — Marietas', category: 'Yacht Rentals', neighborhood: 'Marina', address: 'Marina Vallarta, Puerto Vallarta', latitude: 20.6758, longitude: -105.2578, description: 'Full-day private yacht charter to the Marieta Islands. Up to 12 guests. Captain and crew included, gourmet catering, snorkel gear, kayaks, and paddleboards.', photos: [], rating: 4.8, review_count: 312, price_range: 4, phone: '+52 322 225 5000', website: null, instagram: '@pvyachtcharter', tags: ['Private','Charter','Full Day','Luxury','Snorkeling','Up to 12 guests'], is_premium: true, is_featured: false, is_open: true, open_hours: 'Daily 8:00 AM – 6:00 PM', is_lgbt_friendly: false },
  { name: 'Luxury Catamaran Snorkel Tour', category: 'Yacht Rentals', neighborhood: 'Marina', address: 'Marina Vallarta Pier 3, Puerto Vallarta', latitude: 20.6762, longitude: -105.2582, description: '5-hour luxury catamaran tour to Majahuitas private beach. All-inclusive open bar, gourmet deli lunch, snorkeling gear, and paddleboards. Max 18 guests.', photos: [], rating: 4.6, review_count: 530, price_range: 3, phone: '+52 322 225 6789', website: null, instagram: '@pvluxurycatamaran', tags: ['Catamaran','Snorkeling','All-Inclusive','Lunch','Private Beach','Small Group'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Daily 9:00 AM – 2:00 PM', is_lgbt_friendly: false },
  { name: 'Sport Fishing Charter PV', category: 'Yacht Rentals', neighborhood: 'Marina', address: 'Marina Vallarta, Charter Dock, Puerto Vallarta', latitude: 20.6756, longitude: -105.2576, description: 'Deep-sea fishing in the rich waters of Banderas Bay. Target marlin, dorado, sailfish, and yellowfin tuna. Half and full-day charters. Equipment included.', photos: [], rating: 4.7, review_count: 687, price_range: 3, phone: '+52 322 225 8888', website: null, instagram: '@pvfishingcharters', tags: ['Fishing','Deep Sea','Marlin','Dorado','Half Day','Full Day'], is_premium: true, is_featured: false, is_open: true, open_hours: 'Daily 6:00 AM – 4:00 PM', is_lgbt_friendly: false },
  { name: 'Pirate Ship Marigalante', category: 'Yacht Rentals', neighborhood: 'Marina', address: 'Marina Vallarta, Puerto Vallarta', latitude: 20.6754, longitude: -105.2575, description: 'Iconic pirate ship cruise along the bay. Dinner and show by night, beach excursion by day. Open bar, buffet, cannon fire, and pirate performances.', photos: [], rating: 4.5, review_count: 2156, price_range: 3, phone: '+52 322 223 0309', website: 'https://marigalante.com.mx', instagram: '@marigalantepv', tags: ['Pirate Ship','Entertainment','Dinner Show','Family','Open Bar','Iconic'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Daily Departures 10:00 AM & 7:00 PM', is_lgbt_friendly: false },

  // CAR & MOTO RENTAL (5)
  { name: 'Vallarta Car Rental', category: 'Car & Moto Rental', neighborhood: 'Hotel Zone', address: 'Blvd. Francisco Medina Ascencio 8060, Hotel Zone, Puerto Vallarta', latitude: 20.6610, longitude: -105.2478, description: 'Best rates on car rentals in Puerto Vallarta. Large fleet of economy cars, SUVs, and convertibles. Airport pickup available. English-speaking staff.', photos: [], rating: 4.5, review_count: 678, price_range: 2, phone: '+52 322 222 0999', website: null, instagram: null, tags: ['Car Rental','Airport','SUV','Economy','Convertible'], is_premium: true, is_featured: false, is_open: true, open_hours: 'Daily 8:00 AM – 8:00 PM', is_lgbt_friendly: false },
  { name: 'Moto Rent PV', category: 'Car & Moto Rental', neighborhood: 'Zona Romántica', address: 'Olas Altas 390, Zona Romántica, Puerto Vallarta', latitude: 20.5988, longitude: -105.2371, description: 'Scooters, motorbikes, and ATVs for rent by the hour or day. Helmets and insurance always included. Best way to explore the coast.', photos: [], rating: 4.6, review_count: 289, price_range: 1, phone: '+52 322 222 1234', website: null, instagram: '@motorentpv', tags: ['Moto','Scooter','ATV','Hourly','Daily','Helmets Included'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 9:00 AM – 7:00 PM', is_lgbt_friendly: false },
  { name: 'Budget Rent a Car Puerto Vallarta', category: 'Car & Moto Rental', neighborhood: 'Hotel Zone', address: 'Blvd. Francisco Medina Ascencio 1728, Hotel Zone, Puerto Vallarta', latitude: 20.6381, longitude: -105.2434, description: 'International car rental brand with PV airport counter and hotel zone office. Wide selection, competitive rates, and 24/7 roadside assistance.', photos: [], rating: 4.3, review_count: 1234, price_range: 2, phone: '+52 322 221 1730', website: 'https://budget.com.mx', instagram: null, tags: ['Car Rental','International','Airport Counter','24/7 Support'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 7:00 AM – 10:00 PM', is_lgbt_friendly: false },
  { name: 'PV Golf Carts & UTV Rentals', category: 'Car & Moto Rental', neighborhood: 'Nuevo Vallarta', address: 'Blvd. Nuevo Vallarta 100, Nuevo Vallarta, Nayarit', latitude: 20.7095, longitude: -105.2978, description: 'Golf carts, UTVs, and side-by-sides for exploring Nuevo Vallarta and the Riviera Nayarit. Hourly and daily rates. Perfect for beach access.', photos: [], rating: 4.4, review_count: 187, price_range: 2, phone: '+52 329 297 0123', website: null, instagram: '@pvgolfcarts', tags: ['Golf Cart','UTV','Nuevo Vallarta','Beach Access','Hourly'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 8:00 AM – 6:00 PM', is_lgbt_friendly: false },
  { name: 'Cycling PV — Bike Tours & Rentals', category: 'Car & Moto Rental', neighborhood: 'Centro', address: 'Insurgentes 242, Centro, Puerto Vallarta', latitude: 20.6031, longitude: -105.2360, description: 'Bike rentals and guided cycling tours through Puerto Vallarta. Explore the Malecon, Zona Romántica, and hidden neighborhoods. E-bikes available.', photos: [], rating: 4.7, review_count: 312, price_range: 1, phone: '+52 322 222 6453', website: null, instagram: '@cyclingpv', tags: ['Bike','E-Bike','Tours','Rental','Malecon','Eco-Friendly'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 8:00 AM – 6:00 PM', is_lgbt_friendly: true },

  // BEACHES (6)
  { name: 'Playa Los Muertos', category: 'Beaches', neighborhood: 'Zona Romántica', address: 'Playa Los Muertos, Zona Romántica, Puerto Vallarta', latitude: 20.5970, longitude: -105.2400, description: "Puerto Vallarta's most famous and vibrant beach. Gay-friendly south end (Blue Chairs), beach restaurants and bars, volleyball, parasailing, and legendary sunsets.", photos: [], rating: 4.8, review_count: 4521, price_range: 0, phone: null, website: null, instagram: null, tags: ['LGBT+ Friendly','Beach Bars','Sunset','Volleyball','Parasailing','Central'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Always open', is_lgbt_friendly: true },
  { name: 'Playa Sayulita', category: 'Beaches', neighborhood: 'Sayulita', address: 'Sayulita, Nayarit', latitude: 20.8685, longitude: -105.4458, description: 'Charming bohemian surf beach 45 min north of PV. Mexican fishermen, surfers, and travelers coexist. Colorful town, excellent tacos, surf rentals, and a relaxed vibe.', photos: [], rating: 4.7, review_count: 2134, price_range: 0, phone: null, website: null, instagram: null, tags: ['Surf','Bohemian','Village','Colorful','Fishing','Day Trip'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Always open', is_lgbt_friendly: false },
  { name: 'Playa Conchas Chinas', category: 'Beaches', neighborhood: 'Hotel Zone', address: 'Carretera a Barra de Navidad, Puerto Vallarta', latitude: 20.5898, longitude: -105.2418, description: 'Secluded cove beach 2km south of the Romantic Zone. Rocky outcroppings create natural pools perfect for snorkeling. Quieter and more pristine than Los Muertos.', photos: [], rating: 4.6, review_count: 876, price_range: 0, phone: null, website: null, instagram: null, tags: ['Secluded','Snorkeling','Rocky','Natural Pools','Quiet'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Always open', is_lgbt_friendly: false },
  { name: 'Playa Mismaloya', category: 'Beaches', neighborhood: 'Hotel Zone', address: 'Mismaloya, Puerto Vallarta, Jalisco', latitude: 20.5555, longitude: -105.2470, description: 'Historic beach where John Huston filmed Night of the Iguana in 1963. Stunning backdrop of jungle mountains, river mouth, and the Los Arcos rocks offshore.', photos: [], rating: 4.5, review_count: 1243, price_range: 0, phone: null, website: null, instagram: null, tags: ['Historic','Film Location','Jungle','River','Los Arcos','Photography'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Always open', is_lgbt_friendly: false },
  { name: 'Playa Punta Mita', category: 'Beaches', neighborhood: 'Punta Mita', address: 'Punta de Mita, Nayarit', latitude: 20.7720, longitude: -105.5000, description: 'The exclusive northern peninsula with pristine white sand beaches and crystal-clear water. Home to world-class resorts, surf breaks, and the Four Seasons.', photos: [], rating: 4.8, review_count: 1567, price_range: 0, phone: null, website: null, instagram: null, tags: ['Luxury','White Sand','Surf','Four Seasons','Exclusive','Crystal Clear'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Always open', is_lgbt_friendly: false },
  { name: 'Playa Bucerías', category: 'Beaches', neighborhood: 'Bucerías', address: 'Bucerías, Nayarit', latitude: 20.7502, longitude: -105.3310, description: 'Charming fishing village north of PV with a long stretch of golden sand. Excellent seafood restaurants on the beach, colorful streets, and a relaxed expat community.', photos: [], rating: 4.6, review_count: 987, price_range: 0, phone: null, website: null, instagram: null, tags: ['Fishing Village','Long Beach','Seafood','Expat','Charming','Relaxed'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Always open', is_lgbt_friendly: false },

  // SHOPPING (5)
  { name: 'Mercado de Artesanías', category: 'Shopping', neighborhood: 'Centro', address: 'Agustín Rodríguez 164, Centro, Puerto Vallarta', latitude: 20.6042, longitude: -105.2348, description: "Puerto Vallarta's famous artisan market. Huichol beadwork, Talavera ceramics, handwoven textiles, leather goods, and silver jewelry.", photos: [], rating: 4.5, review_count: 1872, price_range: 1, phone: null, website: null, instagram: null, tags: ['Artisan','Souvenirs','Huichol','Handmade','Market','Bargain'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Daily 9:00 AM – 8:00 PM', is_lgbt_friendly: false },
  { name: 'Galería Dante', category: 'Shopping', neighborhood: 'Centro', address: 'Basilio Badillo 269, Centro, Puerto Vallarta', latitude: 20.6028, longitude: -105.2368, description: "PV's most important art gallery with over 30 years. Sculptures, paintings, and bronze work by top Mexican and international artists. Free to browse.", photos: [], rating: 4.7, review_count: 543, price_range: 3, phone: '+52 322 222 2477', website: 'https://galeriadante.com', instagram: '@galeriadante', tags: ['Art Gallery','Sculpture','Painting','Mexican Art','Bronze','Free Entry'], is_premium: false, is_featured: true, is_open: true, open_hours: 'Mon–Sat 10:00 AM – 6:00 PM', is_lgbt_friendly: false },
  { name: 'La Comer Supermarket', category: 'Shopping', neighborhood: 'Hotel Zone', address: 'Blvd. Francisco Medina Ascencio 2900, Hotel Zone, Puerto Vallarta', latitude: 20.6398, longitude: -105.2418, description: 'Major supermarket for stocking up on groceries, snacks, mezcal, tequila, and everyday items. Essential stop for longer stays or villa rentals.', photos: [], rating: 4.3, review_count: 2341, price_range: 1, phone: '+52 322 226 0700', website: null, instagram: null, tags: ['Supermarket','Groceries','Tequila','Mezcal','Essentials'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 7:00 AM – 11:00 PM', is_lgbt_friendly: false },
  { name: 'Mundo de Cristal', category: 'Shopping', neighborhood: 'Centro', address: 'Insurgentes 333, Centro, Puerto Vallarta', latitude: 20.6033, longitude: -105.2363, description: 'Stunning Talavera ceramics, blown glass, and home decor direct from the artisans of Jalisco and Guanajuato. Unique pieces impossible to find elsewhere.', photos: [], rating: 4.6, review_count: 678, price_range: 2, phone: '+52 322 222 4157', website: null, instagram: null, tags: ['Talavera','Blown Glass','Home Decor','Artisan','Jalisco','Gifts'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Mon–Sat 10:00 AM – 7:00 PM', is_lgbt_friendly: false },
  { name: 'Flea Market Malecon', category: 'Shopping', neighborhood: 'Centro', address: 'Paseo Díaz Ordaz, Centro, Puerto Vallarta', latitude: 20.6058, longitude: -105.2342, description: 'Open-air weekend market along the iconic Malecon boardwalk. Local vendors selling handmade jewelry, artwork, clothing, and unique souvenirs.', photos: [], rating: 4.4, review_count: 934, price_range: 1, phone: null, website: null, instagram: null, tags: ['Market','Weekend','Malecon','Jewelry','Handmade','Open Air'], is_premium: false, is_featured: false, is_open: false, open_hours: 'Sat–Sun 10:00 AM – 6:00 PM', is_lgbt_friendly: true },

  // SPAS & WELLNESS (5)
  { name: 'Garza Blanca Spa', category: 'Spas & Wellness', neighborhood: 'Hotel Zone', address: 'Carr. Barra de Navidad Km 7.5, Puerto Vallarta', latitude: 20.5612, longitude: -105.2572, description: 'World-class spa at Garza Blanca Resort. Signature treatments inspired by Mexican healing traditions, ocean views, hydrotherapy circuit, and luxury couples suites.', photos: [], rating: 4.9, review_count: 456, price_range: 4, phone: '+52 322 176 0700', website: 'https://garzablanca.com/spa', instagram: '@garzablancaspa', tags: ['Luxury Spa','Couples','Hydrotherapy','Ocean Views','Mexican Traditions'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 9:00 AM – 9:00 PM', is_lgbt_friendly: false },
  { name: 'Spa Xinalani', category: 'Spas & Wellness', neighborhood: 'Centro', address: 'Playa Quimixto s/n, Puerto Vallarta (boat access only)', latitude: 20.5103, longitude: -105.2812, description: 'Remote jungle eco-resort spa accessible only by boat. Yoga retreat, temazcal, ocean-view massage platforms, and holistic wellness programs.', photos: [], rating: 4.9, review_count: 287, price_range: 4, phone: '+52 322 688 9012', website: 'https://xinalani.com', instagram: '@xinalaniretreat', tags: ['Yoga Retreat','Temazcal','Jungle','Eco','Remote','Holistic','Boat Access'], is_premium: true, is_featured: true, is_open: true, open_hours: 'Daily 7:00 AM – 8:00 PM', is_lgbt_friendly: true },
  { name: 'Boca Spa & Wellness PV', category: 'Spas & Wellness', neighborhood: 'Zona Romántica', address: 'Basilio Badillo 371, Zona Romántica, Puerto Vallarta', latitude: 20.6025, longitude: -105.2362, description: 'Award-winning day spa in the Romantic Zone. Deep tissue massage, hot stone therapy, facials, and traditional temazcal. Walk-ins welcome.', photos: [], rating: 4.7, review_count: 412, price_range: 3, phone: '+52 322 223 0308', website: null, instagram: '@bocaspv', tags: ['Day Spa','Massage','Facials','Temazcal','Walk-In','Romantic Zone'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Mon–Sat 10:00 AM – 8:00 PM', is_lgbt_friendly: true },
  { name: 'Temazcal Ritual & Yoga PV', category: 'Spas & Wellness', neighborhood: 'Centro', address: 'Carr. a Boca de Tomatlán Km 1.5, Puerto Vallarta', latitude: 20.5651, longitude: -105.2480, description: 'Authentic temazcal (Aztec sweat lodge) ceremony led by a traditional healer. Followed by river swimming and yoga session. Deeply spiritual and cleansing.', photos: [], rating: 4.8, review_count: 234, price_range: 2, phone: '+52 322 140 2345', website: null, instagram: '@temazcalpv', tags: ['Temazcal','Traditional','Curandera','Yoga','River','Spiritual','Cultural'], is_premium: false, is_featured: false, is_open: true, open_hours: 'By appointment — Tue–Sun', is_lgbt_friendly: false },
  { name: 'Casa de los Sueños Wellness', category: 'Spas & Wellness', neighborhood: 'Zona Romántica', address: 'Amapas 115, Zona Romántica, Puerto Vallarta', latitude: 20.5980, longitude: -105.2368, description: 'Intimate hillside wellness retreat with ocean views. CBD massages, sound healing, crystal therapy, and meditation sessions. Adults only.', photos: [], rating: 4.8, review_count: 178, price_range: 3, phone: '+52 322 223 1900', website: null, instagram: '@casasuenoswellness', tags: ['CBD Massage','Sound Healing','Meditation','Ocean Views','Adults Only'], is_premium: false, is_featured: false, is_open: true, open_hours: 'Daily 9:00 AM – 7:00 PM', is_lgbt_friendly: true },
]

const events = [
  { title: 'Vallarta Pride 2026', description: "Puerto Vallarta's annual Pride celebration — one of the largest in Latin America. Week-long festivities including beach parties, parades, drag shows, live concerts, and cultural events throughout Zona Romántica.", neighborhood: 'Zona Romántica', address: 'Zona Romántica, Puerto Vallarta', latitude: 20.5982, longitude: -105.2375, start_date: '2026-05-18T10:00:00-06:00', end_date: '2026-05-24T23:00:00-06:00', is_public: true, is_free: true, ticket_price: null, ticket_url: 'https://vallartapride.com', photos: [], tags: ['LGBT+','Pride','Festival','Beach Party','Parade','Annual'], organizer: 'Vallarta Pride', instagram: '@vallartapride', is_featured: true, is_lgbt_friendly: true, is_recurring: true, recurrence_label: 'Annual — May' },
  { title: 'Moonlight Jazz at the Marina', description: 'Monthly rooftop jazz nights at Marina Vallarta with live trio, open bar, and panoramic bay views. Smart casual dress code. Limited to 80 guests. Reservations required.', neighborhood: 'Marina', address: 'Marina Vallarta Rooftop, Puerto Vallarta', latitude: 20.6720, longitude: -105.2545, start_date: '2026-04-18T20:00:00-06:00', end_date: '2026-04-19T00:00:00-06:00', is_public: false, is_free: false, ticket_price: 850, ticket_url: null, photos: [], tags: ['Jazz','Live Music','Rooftop','Marina','Private','Open Bar'], organizer: 'Marina Events PV', instagram: '@marinajazzpv', is_featured: true, is_lgbt_friendly: false, is_recurring: true, recurrence_label: 'Monthly — 3rd Saturday' },
  { title: 'Sayulita Surf Competition', description: 'Annual amateur and pro surf competition at Playa Sayulita. Watch local and international surfers compete in longboard, shortboard, and SUP categories. Free to watch on the beach.', neighborhood: 'Sayulita', address: 'Playa Sayulita, Sayulita, Nayarit', latitude: 20.8685, longitude: -105.4458, start_date: '2026-11-07T08:00:00-06:00', end_date: '2026-11-09T18:00:00-06:00', is_public: true, is_free: true, ticket_price: null, ticket_url: null, photos: [], tags: ['Surfing','Competition','Sayulita','Amateur','Pro','Annual'], organizer: 'Sayulita Surf Club', instagram: '@sayulitasurfcomp', is_featured: false, is_lgbt_friendly: false, is_recurring: true, recurrence_label: 'Annual — November' },
  { title: 'Gourmet Food & Wine Festival', description: "Puerto Vallarta's most prestigious culinary event. 10 days of wine pairings, celebrity chef dinners, cooking classes, and gourmet tastings at venues across the city.", neighborhood: 'Centro', address: 'Various venues, Puerto Vallarta', latitude: 20.6054, longitude: -105.2350, start_date: '2026-11-13T12:00:00-06:00', end_date: '2026-11-22T23:00:00-06:00', is_public: true, is_free: false, ticket_price: 1500, ticket_url: 'https://festivalgourmetpv.com', photos: [], tags: ['Food','Wine','Gourmet','Celebrity Chefs','Annual'], organizer: 'Festival Gourmet Internacional', instagram: '@festivalgourmetpv', is_featured: true, is_lgbt_friendly: false, is_recurring: true, recurrence_label: 'Annual — November' },
  { title: 'Thursday Night Art Walk', description: "Every Thursday evening, Centro and Gringo Gulch galleries open their doors for free. Walk between 20+ galleries, meet the artists, enjoy wine and snacks, and discover PV's thriving art scene.", neighborhood: 'Centro', address: 'Centro Histórico, Puerto Vallarta', latitude: 20.6050, longitude: -105.2352, start_date: '2026-04-09T18:00:00-06:00', end_date: '2026-04-09T22:00:00-06:00', is_public: true, is_free: true, ticket_price: null, ticket_url: null, photos: [], tags: ['Art','Galleries','Walking Tour','Free','Wine','Weekly','Culture'], organizer: 'PV Art Galleries Association', instagram: '@pvartwalks', is_featured: false, is_lgbt_friendly: true, is_recurring: true, recurrence_label: 'Every Thursday 6:00 PM – 10:00 PM' },
  { title: 'Sunset Beach Party — Blue Chairs', description: 'The legendary daily sunset party at Blue Chairs LGBT+ beach club. Drag shows on the sand, DJ music, cold cocktails, and the best people-watching in PV.', neighborhood: 'Zona Romántica', address: 'Blue Chairs Beach Club, Playa Los Muertos, Puerto Vallarta', latitude: 20.5975, longitude: -105.2395, start_date: '2026-04-07T17:00:00-06:00', end_date: '2026-04-07T21:00:00-06:00', is_public: true, is_free: true, ticket_price: null, ticket_url: null, photos: [], tags: ['LGBT+','Sunset','Drag Show','DJ','Beach Party','Daily'], organizer: 'Blue Chairs Resort', instagram: '@bluechairspv', is_featured: true, is_lgbt_friendly: true, is_recurring: true, recurrence_label: 'Daily 5:00 PM – 9:00 PM' },
]

async function seed() {
  console.log('Seeding VallartApp database...\n')

  console.log('Clearing existing data...')
  await supabase.from('reviews').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  await supabase.from('events').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  await supabase.from('listings').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  console.log('Cleared\n')

  console.log(`Inserting ${listings.length} listings...`)
  const batchSize = 10
  for (let i = 0; i < listings.length; i += batchSize) {
    const batch = listings.slice(i, i + batchSize)
    const { error } = await supabase.from('listings').insert(batch)
    if (error) { console.error(`Error in batch ${Math.floor(i/batchSize)+1}:`, error.message); process.exit(1) }
    console.log(`  Batch ${Math.floor(i/batchSize)+1}: inserted ${batch.length}`)
  }

  console.log(`\nInserting ${events.length} events...`)
  const { error: eventsError } = await supabase.from('events').insert(events)
  if (eventsError) { console.error('Error inserting events:', eventsError.message); process.exit(1) }
  console.log('  All events inserted')

  const { count: lc } = await supabase.from('listings').select('*', { count: 'exact', head: true })
  const { count: ec } = await supabase.from('events').select('*', { count: 'exact', head: true })
  console.log(`\nDone! ${lc} listings + ${ec} events in database`)

  const cats = ['Restaurants','Bars & Nightlife','Hotels','Activities','Yacht Rentals','Car & Moto Rental','Beaches','Shopping','Spas & Wellness']
  for (const cat of cats) {
    console.log(`  ${cat}: ${listings.filter(l => l.category === cat).length}`)
  }
}

seed().catch(console.error)
